env:
  global:
    secure: "ZwRocRs3G13Gm7ZUDj5yZHGlLgBnlyMmUTduBEex0fhEZIOIZhLZtyasKTxHyi4M/p1+5oxDjyDksUTWQ/DPz03zodu5zfe4qnx/jeiNA0qZgppwf3Qh5JIy/1lYLjiXFyp3OQHuQwAqsELxWPnQt1Xjg2yoXNyy3ZXKtTgjtM8="
language: java
jdk:
  - oraclejdk8
